import { Flashcard } from "./api";

export const MOCK_CARDS: Flashcard[] = [
  { id: 1, question: "What is the purpose of a Risk Register?", answer: "A Risk Register is a document that records identified risks, their probability, impact, mitigation strategies, and owners. It serves as the central tool for tracking and managing project risks throughout the project lifecycle.", difficulty: "medium", next_review_at: null },
  { id: 2, question: "Define Earned Value (EV) in project management.", answer: "Earned Value (EV) is the budgeted cost of work that has actually been performed. It measures the value of work completed in terms of the approved budget, allowing comparison against planned and actual costs.", difficulty: "hard", next_review_at: null },
  { id: 3, question: "What does a Schedule Performance Index (SPI) of 0.8 indicate?", answer: "An SPI of 0.8 means the project is only accomplishing 80% of the planned work — the project is behind schedule. SPI < 1 indicates schedule delay; SPI > 1 means ahead of schedule.", difficulty: "hard", next_review_at: null },
  { id: 4, question: "What is the difference between a stakeholder and a sponsor?", answer: "A stakeholder is anyone affected by or who can affect the project outcome. A sponsor is a specific type of stakeholder who provides financial resources and champions the project at the executive level.", difficulty: "easy", next_review_at: null },
  { id: 5, question: "What is Monte Carlo Analysis used for in risk management?", answer: "Monte Carlo Analysis is a quantitative risk technique that runs thousands of simulations using probability distributions of task durations/costs to predict the probability of completing the project within a given time or budget.", difficulty: "hard", next_review_at: null },
  { id: 6, question: "What is the Critical Path Method (CPM)?", answer: "CPM is a schedule network analysis technique that identifies the longest sequence of dependent activities (the critical path), which determines the minimum project duration. Any delay on the critical path delays the whole project.", difficulty: "medium", next_review_at: null },
  { id: 7, question: "Define Cost Variance (CV).", answer: "Cost Variance = Earned Value (EV) − Actual Cost (AC). A positive CV means under budget; a negative CV means over budget.", difficulty: "medium", next_review_at: null },
  { id: 8, question: "What is a RACI matrix?", answer: "A RACI matrix defines roles and responsibilities by assigning each task one of four statuses: Responsible (does the work), Accountable (owns the outcome), Consulted (provides input), Informed (kept up to date).", difficulty: "easy", next_review_at: null },
];
